/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "StructureExample.h"

// definicion de variables
int counter_i = 0;
BasicExample muestraA = {0};


int main(void)
{
	muestraA.ID = 28;
	muestraA.counterUp = 1;
	muestraA.dummy = 87;
	muestraA.repetitions = 40;
	muestraA.timestamp = 12345678;
    /* Loop forever */
	while(1){
		for(counter_i = 0; counter_i < muestraA.repetitions; counter_i++){
		}
	}
	return 0;
}
