/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411xx_hal.h"


uint32_t counter;
uint32_t auxCounter;
uint32_t *ptr_counter;
uint8_t byte_Variable;
uint8_t *ptr_byte_Variable;


int main(void)
{

	//trabajando con la variable de 32 bit
	counter = 12345; //Asignando un valor a la variable
	auxCounter = counter; // C es pasado por valor!!!! pasamos a auxCounter el valor de counter

		// hacemos que el puntero apunte a una variable
	ptr_counter = &counter; // asignamos el puntero* a la posición de memoria de counter

	//cambiar el valor almacenado en la memoria a donde está apuntando el puntero*
	*ptr_counter = 43658709;
	ptr_counter++;
	*ptr_counter = 43658709;

	byte_Variable = 32;
	ptr_byte_Variable = &byte_Variable;
	*ptr_byte_Variable = 123;

	// intentando mezclar punteros
	auxCounter = (uint32_t)&counter;	//haciendo un cast
	ptr_byte_Variable = (uint8_t *)auxCounter;
	//se hace un cambio truculento e irresponsable de el valor
	//de la posición de memoria
	//esto no lo espera la maquina
	*ptr_byte_Variable =1;




    /* Loop forever */
	while(1){

	}
	return 0;
}
