/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stm32f4xx.h>
#include <stdint.h>
#include "GPIOxDriver.h"
#include "BasicTimer.h"

uint32_t counter_2 = 0;
uint32_t counter_3 = 0;
uint32_t counter_4 = 0;
uint32_t counter_5 = 0;
uint8_t	selector	=1;



//Definicion de un elemento
GPIO_Handler_t handlerLed = {0}; //PA5
BasicTimer_Handler_t	timer2	= {0};
BasicTimer_Handler_t	timer3	= {0};
BasicTimer_Handler_t	timer4	= {0};
BasicTimer_Handler_t	timer5	= {0};
GPIO_Handler_t handlerUserButton = {0};



void init_Hardware(void);
void BasicTimerX_Callback(void);

int main(void){

	init_Hardware();
	while(1){

		if((GPIO_ReadPin(&handlerUserButton))== 0){
			selector++;
			if(selector > 4){
				selector = 1;
			}

		}
	}		//Fin del ciclo princial
}



void init_Hardware(void){

    // Configurando el LED 2-> PA5
	handlerLed.pGPIOx								= GPIOA;
	handlerLed.GPIO_PinConfig.GPIO_PinNumber		= PIN_5;
	handlerLed.GPIO_PinConfig.GPIO_PinMode			= GPIO_MODE_OUT;
	handlerLed.GPIO_PinConfig.GPIO_PinOPType		= GPIO_OTYPE_PUSHPULL;
	handlerLed.GPIO_PinConfig.GPIO_PinSpeed			= GPIO_OSPEED_FAST;
	handlerLed.GPIO_PinConfig.GPIO_PinPuPdControl	= GPIO_PUPDR_NOTHING;
	//Cargamos la configuracion del PIN A5
	GPIO_Config(&handlerLed);


	//Configurando el TIM2
	timer2.ptrTIMx							= TIM2;
	timer2.TIMx_Config.TIMx_mode			= BTIMER_MODE_UP;
	timer2.TIMx_Config.TIMx_speed			= BTIMER_SPEED_1ms;
	timer2.TIMx_Config.TIMx_period			= 2000;
	timer2.TIMx_Config.TIMx_interruptEnable	= BTIMER_INTERRUPT_ENABLE;
	//Configurando el TIM3
	timer3.ptrTIMx							= TIM3;
	timer3.TIMx_Config.TIMx_mode			= BTIMER_MODE_UP;
	timer3.TIMx_Config.TIMx_speed			= BTIMER_SPEED_100us;
	timer3.TIMx_Config.TIMx_period			= 1000;
	timer3.TIMx_Config.TIMx_interruptEnable	= BTIMER_INTERRUPT_ENABLE;
	//Configurando el TIM4
	timer4.ptrTIMx							= TIM4;
	timer4.TIMx_Config.TIMx_mode			= BTIMER_MODE_UP;
	timer4.TIMx_Config.TIMx_speed			= BTIMER_SPEED_10us;
	timer4.TIMx_Config.TIMx_period			= 100000;
	timer4.TIMx_Config.TIMx_interruptEnable	= BTIMER_INTERRUPT_ENABLE;
	//Configurando el TIM5
	timer5.ptrTIMx							= TIM5;
	timer5.TIMx_Config.TIMx_mode			= BTIMER_MODE_UP;
	timer5.TIMx_Config.TIMx_speed			= BTIMER_SPEED_1ms;
	timer5.TIMx_Config.TIMx_period			= 1000;
	timer5.TIMx_Config.TIMx_interruptEnable	= BTIMER_INTERRUPT_ENABLE;
	//	BOTON
	handlerUserButton.pGPIOx 								= GPIOC;
	handlerUserButton.GPIO_PinConfig.GPIO_PinNumber			= PIN_13;
	handlerUserButton.GPIO_PinConfig.GPIO_PinMode			= GPIO_MODE_IN;
	handlerUserButton.GPIO_PinConfig.GPIO_PinPuPdControl	= GPIO_PUPDR_NOTHING;
	handlerUserButton.GPIO_PinConfig.GPIO_PinAltFunMode		= AF0;

	//Cargamos la configuracion del TIM2
	BasicTimer_Config(&timer2);
	BasicTimer_Config(&timer3);
	BasicTimer_Config(&timer4);
	BasicTimer_Config(&timer5);
	GPIO_Config(&handlerUserButton);
}


void BasicTimer2_Callback(void){
	counter_2++;
	if(selector ==1){
		GPIOxTogglePin(&handlerLed);
	}
//	GPIOxTogglePin(&handlerLed);
}

void BasicTimer3_Callback(void){
	counter_3++;
	if(selector ==2){
		GPIOxTogglePin(&handlerLed);
	}
//	GPIOxTogglePin(&handlerLed);
}
void BasicTimer4_Callback(void){
	counter_4++;
	if(selector ==3){
		GPIOxTogglePin(&handlerLed);
	}
//	GPIOxTogglePin(&handlerLed);
}
void BasicTimer5_Callback(void){
	counter_5++;
	if(selector ==4){
		GPIOxTogglePin(&handlerLed);
	}
}
