/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stm32f4xx.h>
#include <stdint.h>
#include "GPIOxDriver.h"
#include "BasicTimer.h"

//Definicion de un elemento
BasicTimer_Handler_t handlerTIM1 = {0}; //TIMER1
BasicTimer_Handler_t handlerTIM2 = {0}; //TIMER1
BasicTimer_Handler_t handlerTIM3 = {0}; //TIMER1
BasicTimer_Handler_t handlerTIM4 = {0}; //TIMER1



void EncenderLed(uint8_t counter_i);

int main(void)
{
    // Configurando el LED 2-> PA5
	handlerLed2.pGPIOx								= GPIOA;
	handlerLed2.GPIO_PinConfig.GPIO_PinNumber		= PIN_5;
	handlerLed2.GPIO_PinConfig.GPIO_PinMode			= GPIO_MODE_OUT;
	handlerLed2.GPIO_PinConfig.GPIO_PinOPType		= GPIO_OTYPE_PUSHPULL;
	handlerLed2.GPIO_PinConfig.GPIO_PinSpeed		= GPIO_OSPEED_FAST;
	handlerLed2.GPIO_PinConfig.GPIO_PinPuPdControl	= GPIO_PUPDR_NOTHING;

	//Cargamos la configuracion del PIN A5

	GPIO_Config(&handlerLed2);
	GPIO_WritePin(&handlerLed2, SET);

    // Configurando el TIMER 1-> TIM1
	handlerTIM1.ptrTIMx									=TIM1;
	handlerTIM1.TIMx_Config.TIMx_mode					= BTIMER_MODE_UP;
	handlerTIM1.TIMx_Config.TIMx_speed					= BTIMER_SPEED_1ms;
	handlerTIM1.TIMx_Config.TIMx_period					=
	handlerTIM1.TIMx_Config.TIMx_interruptEnable		= BTIMER_INTERRUPT_ENABLE;

	BasicTimer_Config(&handlerTIM1);



	while(1){

		}
	}
}

//definimos la funcion que enciende el led
void EncenderLed(uint8_t counter_i){

}
