/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>



int main(void){
	//definimos los set de personajes
	uint16_t faceSet =	0b0000011011001110;
	uint16_t faceSet2 =	0b1101100001000111;
	uint32_t faceSet_32b = faceSet <<16;
	uint32_t sumFaceSet = faceSet_32b + faceSet2;
	//definimos las mascaras

	uint16_t mask1 = 0b0;
	uint16_t mask2 = 0b0;

	//desplegamos soluciones
	//posiciones de caras (hombres)
	uint16_t mFace1 = ~faceSet;
	uint16_t mFace2 = ~faceSet2;

	//posiciones femeninas que usan lente
	uint16_t maskLens= (mask1+0b1) << 9;
	uint16_t lens1 = faceSet & maskLens;

	// para el segundo set
	uint16_t maskLens14  = (mask1+0b1) << 14;
	uint16_t maskLens12 = (mask2+0b1) << 12;
	uint16_t mascara = maskLens14 + maskLens12;

	uint16_t resultadoLens  = faceSet2 & mascara;


	//caras masculinas con bigote
	uint16_t maskBigote0 = (mask1+0b1);
	uint16_t maskBigote4 = (mask1+0b1) << 4;
	uint16_t maskBigote8 = (mask2+0b1) << 8;
	uint16_t mascaraBigote  = maskBigote0 + maskBigote4 + maskBigote8;

	uint16_t resultadoBigote  = faceSet | mascaraBigote;


    /* Loop forever */
	while(1){

	}
	return 0;
}
