/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411xx_hal.h"


int main(void)
{
	// Configuracion inicial del MCU
	RCC->AHB1ENR &= ~(1 << 0); //desplazamos el 1 cero veces y lo negamos, así borramos SOLO la posicion 0, conservando el resto
	RCC->AHB1ENR |= 1 << 0; //ponemos un 1 al final y dejamos el resto igual, es necesario "limpiar SIEMPRE el lugar"


	// Configurar MODER
	GPIOA->MODER &= ~(0b11 << 10);		//limpiar la posición correspondiente al PIN5
	GPIOA->MODER |= (0b01 << 10);		//Configurar el pin C5 como salida general
	// config otype
	GPIOA->OTYPER &= ~(0b1 << 5);		// pinC5 configurado como salida Push-Pull
	//config ospeedr
	GPIOA->OSPEEDR &= ~(0b11 << 10);	//limpiar posiciones de pin C5
	GPIOA->OSPEEDR |= (0b01 << 10);	//config la velocidad como Fast


    /* Loop forever */
	while(1){
// Configuramos la salida
	GPIOA->ODR &= ~(0b1 <<5);			//limpiando posición
	GPIOA->ODR |= (0b1 << 5);
	}
}
